In [16]:
# example of a model defined with the sequential api
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
# define the model
model = Sequential()
model.add(Dense(10, input_shape=(8,)))
model.add(Dense(1))

array([[ 0.20612991, -0.05376483,  0.4549252 ,  0.29173946,  0.56487817,
        -0.28051278,  0.3635518 ,  0.00938493,  0.56584555,  0.20877497]],
      dtype=float32)

array([[0.09419144, 0.0726341 , 0.12079859, 0.10261036, 0.13483848,
        0.05789822, 0.11025008, 0.07736886, 0.13496898, 0.09444091]],
      dtype=float32)

2.8490686

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2960 - accuracy: 0.9140

313/313 - 1s - loss: 0.0735 - accuracy: 0.9768 - 637ms/epoch - 2ms/step


[0.07347866147756577, 0.9768000245094299]

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.8927380e-08, 2.2209012e-09, 7.0208182e-07, 1.0368639e-04,
        1.1871761e-10, 1.4653044e-06, 1.6062933e-12, 9.9987912e-01,
        4.1839306e-07, 1.4640815e-05],
       [1.0922928e-08, 5.8250624e-04, 9.9939704e-01, 1.7860499e-05,
        1.1156318e-14, 2.2759739e-06, 1.7618141e-09, 1.8692639e-12,
        2.9890890e-07, 4.9204349e-11],
       [1.2987707e-07, 9.9853289e-01, 6.6613342e-04, 3.1839085e-05,
        3.2443964e-05, 1.7477721e-05, 4.9970176e-06, 5.1271718e-04,
        1.9699636e-04, 4.2790534e-06],
       [9.9958986e-01, 1.1608011e-08, 2.6249274e-04, 2.3732907e-06,
        2.2011147e-06, 4.0690579e-06, 7.3028918e-06, 1.0970805e-05,
        1.2242556e-08, 1.2067144e-04],
       [5.8845035e-06, 2.0997375e-08, 8.2453407e-06, 1.3329679e-07,
        9.8294926e-01, 2.0134684e-07, 1.1801415e-05, 6.0754181e-05,
        9.7303982e-06, 1.6953917e-02]], dtype=float32)>